spring:
  application:
    name: dowoomi
  datasource:
    url: jdbc:sqlite:./data/dowoomi.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  main:
    lazy-initialization: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: kr.geun.oss.dowoomi.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  level:
    kr.geun.oss.dowoomi.domain: DEBUG
